### PR TITLE
Uninitialized variable use

### PR DESCRIPTION
**Pull request by kutayuner**
There is certainly a problem in that commit that introduced those changes. I'm not sure if this change is enough of a fix for my problem but it is a start.
Also I must add that I didn't have the time to test it yet if this fixed the problem completely. Just get sick of waiting over a year for someone else to fix. If it is wrong I'm sure internet will correct it :)

### CODE REVIEW

**Comment by heftig** [comment]
Sorry, this repository does not accept pull requests.

**Comment by kutayuner** [comment]
It was a brainfart anyway but I think I found the real problem. At least fix is working. know what?
Can you help me? What should I do.

**Comment by heftig** [comment]
https://kernelnewbies.org/KernelHacking might be a useful resource.

**Comment by kutayuner** [comment]
thanks

**Comment by ratijas** [comment]
I wonder, there's probably no way to stop people from unintentionally 'referencing' this pull request? Things are getting weird with such common string as `#1` being converted to a link over and over again. Probably should somehow let GitHub stuff know about it...

**Pull request closed without merging**
